eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/
   #defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka
server:
 port: 8765
spring:
 application:
  name: service-hello