spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tomlxq/gs-spring-cloud-config
          searchPaths: respo
          #username: tomlxq
          #password:
      label: master
server:
  port: 8888


